name: Publish docs
on:
  workflow_dispatch:
  repository_dispatch:
    types: [publish-docs]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Checkout pl_common
        uses: actions/checkout@v2.4.2
        with:
          repository: plasmapper/common-esp-cpp
          path: pl_common
          
      - name: Checkout pl_uart
        uses: actions/checkout@v2.4.2
        with:
          repository: plasmapper/uart-esp-cpp
          path: pl_uart
          
      - name: Checkout pl_network
        uses: actions/checkout@v2.4.2
        with:
          repository: plasmapper/network-esp-cpp
          path: pl_network
    
      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          working-directory: docs
      
      - name: Sphinx
        uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: docs
          build-command: sphinx-build source build

      - name: Upload
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: docs/build

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1.1.0
